<?php

// This file was automatically generated by CommonLibrary\ORM\EntityGenerator

namespace kennysLabs\LusoExpress\Infrastructure\Entity;

use kennysLabs\CommonLibrary\ORM\EntityInterface;
use kennysLabs\CommonLibrary\ORM\EntityAbstract;

class Migrations extends EntityAbstract implements EntityInterface {

	const ENTITY_NAME = 'migrations';

	/** @var string $migration */
	private $migration;

	/** @var int $batch */
	private $batch;

	/** @var array $_primaryKeys */
	protected $_primaryKey = [];

	/** @var array $_fields */
	protected $_fields = ['migration', 'batch'];

	/** @var array $uniqueKeys */
	protected $_uniqueKeys = [];

	/**
	 * @return string
	 */
	public function getMigration()
	{
		return $this->migration;
	}

	/**
	 * @param string $value
	 * @return Migrations
	 */
	protected function _setMigration($value)
	{
		$this->migration = $value;
		return $this;
	}

	/**
	 * @return int
	 */
	public function getBatch()
	{
		return $this->batch;
	}

	/**
	 * @param int $value
	 * @return Migrations
	 */
	protected function _setBatch($value)
	{
		$this->batch = $value;
		return $this;
	}

}


