<?php

// This file was automatically generated by CommonLibrary\ORM\EntityGenerator

namespace kennysLabs\LusoExpress\Infrastructure\Entity;

use kennysLabs\CommonLibrary\ORM\EntityInterface;
use kennysLabs\CommonLibrary\ORM\EntityAbstract;

class Users extends EntityAbstract implements EntityInterface {

	const ENTITY_NAME = 'users';

	/** @var string $uuid */
	private $uuid;

	/** @var string $name */
	private $name;

	/** @var string $email */
	private $email;

	/** @var string $password_hash */
	private $password_hash;

	/** @var bool $active */
	private $active;

	/** @var int $role */
	private $role;

	/** @var string $created_at */
	private $created_at;

	/** @var string $updated_at */
	private $updated_at;

	/** @var array $_primaryKeys */
	protected $_primaryKey = ['uuid'];

	/** @var array $_fields */
	protected $_fields = ['uuid', 'name', 'email', 'password_hash', 'active', 'role', 'created_at', 'updated_at'];

	/** @var array $uniqueKeys */
	protected $_uniqueKeys = ['email'];

	/**
	 * @return string
	 */
	public function getUuid()
	{
		return $this->uuid;
	}

	/**
	 * @param string $value
	 */
	protected function _setUuid($value)
	{
		$this->uuid = $value;
	}

	/**
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * @param string $value
	 */
	protected function _setName($value)
	{
		$this->name = $value;
	}

	/**
	 * @return string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * @param string $value
	 */
	protected function _setEmail($value)
	{
		$this->email = $value;
	}

	/**
	 * @return string
	 */
	public function getPasswordHash()
	{
		return $this->password_hash;
	}

	/**
	 * @param string $value
	 */
	protected function _setPasswordHash($value)
	{
		$this->password_hash = $value;
	}

	/**
	 * @return bool
	 */
	public function getActive()
	{
		return $this->active;
	}

	/**
	 * @param bool $value
	 */
	protected function _setActive($value)
	{
		$this->active = $value;
	}

	/**
	 * @return int
	 */
	public function getRole()
	{
		return $this->role;
	}

	/**
	 * @param int $value
	 */
	protected function _setRole($value)
	{
		$this->role = $value;
	}

	/**
	 * @return string
	 */
	public function getCreatedAt()
	{
		return $this->created_at;
	}

	/**
	 * @param string $value
	 */
	protected function _setCreatedAt($value)
	{
		$this->created_at = $value;
	}

	/**
	 * @return string
	 */
	public function getUpdatedAt()
	{
		return $this->updated_at;
	}

	/**
	 * @param string $value
	 */
	protected function _setUpdatedAt($value)
	{
		$this->updated_at = $value;
	}

}


